### ISSUE TITLE
[Fix] 앱을 삭제해도 currentUser가 남아있는 zombie user 문제를 해결합니다.

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#301]
### 📝 작업 목적

실기기 테스트 중 앱을 완전히 삭제하고 다시 빌드해도 currentUser가 남아있어 Auto Login이 진행되는 문제를 해결합니다.

---

### 🛠️ Tasks

* [x] 시뮬레이션에서 테스트해보기
   * 앱을 삭제하고 다시 빌드할 경우, currentUser가 남아있어 reauthenticate 로직이 수행된다.
   * 그래서 기기에 당연히 없는 AT에 접근하려고 해서 문제가 발생한다.
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/50159740/225243453-51a905d0-8dfe-4aa3-bfe9-5b9503a9b134.png">

* [x] 실기기에서 테스트해보기
* [x] 원인 파악하기
   * currentUser를 찍어보자.
* [x] 해결하기
  * UserDefault에 저장되어 있는 AT값도 있어야 하므로, 이 값이 있는지 여부도 자동 로그인 분기 처리에 추가하였다.
  * 우회하여 문제를 해결한 상태이다.

**Comment by guguhanogu** [comment]
🧟🧟‍♂️🧟‍♀️

**Comment by ValseLee** [comment]
🧟‍♂️🧟‍♂️🧟‍♂️🧟‍♂️🧟‍♂️
